apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    #pod들을 target에 match하고 expose 하기 위한 레이블
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    # 사용하는 네트워크 프로토콜
    - protocol: TCP
      #서비스가 노출트는 포트
      port: 80
      # pod가 노출하는 포트이자 서비스가 target하는 포트
      targetPort: 9001